Controllers/CartController.cs
using BilliWebApp.Models.Cart;
using BilliWebApp.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Cors;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BilliWebApp.Controllers
{
    [Authorize]
    [Route("[controller]")]

    public class CartController : Controller
    {
        private CartService _service;

        public CartController(CartService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Cart()
        {
            return View(await _service.GetCart(UserId));
        }

        string UserId
        { 
            get => User.Claims.First(c => Equals(c.Type, "id"))?.Value;
        }

        [HttpPost(nameof(AddToCart))]
        public async Task<IActionResult> AddToCart(AddToCartProduct model)
        {
            if (!await _service.AddToCart(model, UserId))
            {
                return BadRequest();
            }
            return Ok();
        }
    }
}

Controllers/MotorcycleController.cs
using BilliWebApp.Models.Motorcycle;
using BilliWebApp.Services;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace BilliWebApp.Controllers
{
    public class MotorcycleController : Controller
    {
        private MotorcycleService _service;

        public MotorcycleController(MotorcycleService service)
        {
            _service = service;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ProductDetails(string id)
        {
            return View(_service.GetMotorcycle(id));
        }

        public async Task<IActionResult> Products()
        {
            return View(await _service.GetMotorcyclesAsync());
        }

        [HttpPost]
        public void SetImage()
        {
            var x = Request.Form.Files;
        }

        public IActionResult AddProduct()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddProduct(AddMotorcycle model)
        {
            if (!await _service.AddMotorcycle(model)) 
            {
                return View();
            }
            return RedirectToAction(nameof(Products));
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Billi</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Syncopate:wght@700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Motorcycle" asp-action="Index">Billi</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Motorcycle" asp-action="Products">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Cart">Cart</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div>
            <div class="footer">
                <div class="container-2">
                    <div class="row0">
                        <div class="footer-col-1">
                            <ul>
                                <li> <a asp-area="" asp-controller="Home" asp-action="About">ABOUT US</a> </li>
                                <li> <a asp-area="" asp-controller="Home" asp-action="Privacy">PRIVACY POLICY</a> </li>
                                <li> <a asp-area="" asp-controller="Home" asp-action="Contact">CONTACT</a> </li>
                            </ul>
                        </div>
                    </div>
                    <hr>
                    &copy; 2021 - Billi 
                </div>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>